.\"------------------------------------------------------------
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" SPDX-License-Identifier: GPL-2.0-only
.Os
.Dd Jan 1 2026
.Dt BAD_MAN_PAGE 8
.Sh NAME
.Nd "does something totally different from what the file name implies"   
.Nm mismatched
.Sh SEE ALSO
.Xr ls 1
.Sh SYNOPSIS
.Cd "device pci"
.Nm mismatched
.Ar arg
.Pp
Alternatively, to load the driver as a
module at boot time, place the following line in
.Xr loader.conf 5 :
.Sh EXAMPLES
Do a thing that keeps rambling on and on and on and on and on and on and on and on and on and on and on and on forever without ever wrapping the line at any reasonable width whatsoever.
.Xr ichwd 4 Ns 's
.Va dev.hfsts.N
.Dl "sysctl dev.hfsts.0"
