[package]
name = "dictator-typescript"
version = "0.24.0"
description = "TypeScript/JavaScript decree for Dictator structural linter"
edition.workspace = true
rust-version.workspace = true
authors.workspace = true
license.workspace = true
documentation = "https://docs.rs/dictator-typescript"

[lints]
workspace = true

[dependencies]
dictator-decree-abi.workspace = true
dictator-core = { version = "0.24.0", path = "../dictator-core" }
dictator-supreme.workspace = true
memchr = "2"

[lib]
crate-type = ["lib", "cdylib"]
